### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by Yoda-Man** [Adityapanther/flutter-touch-ripple-effect#12]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':touch_ripple_effect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by Adityapanther** [comment]
@Yoda-Man thanks for reporting I will update it soon

**Comment by Adityapanther** [comment]
@Yoda-Man issue has been fixed, please proceed

**Comment by Yoda-Man** [comment]
Thank you
